### PR TITLE
Add Bullet (port from ign-physics3)

### PR DESCRIPTION
**Pull request by chapulina**
Forward port https://github.com/ignition-release/ign-physics3-release/pull/3/

### CODE REVIEW

**Comment by j-rivero** [comment]
Do we want to include the libignition-physics4-bullet-dev in the libignition-physics4-dev metapackage?

**Comment by chapulina** [comment]
> Do we want to include the libignition-physics4-bullet-dev in the libignition-physics4-dev metapackage?

Same situation as in https://github.com/ignition-release/ign-physics3-release/pull/3#issuecomment-863473674, let's do that from `ign-physics5`, which is Fortress.

**Comment by scpeters** [comment]
oops, I forgot about this and submitted #12

this PR has some incorrect symlink files with `libignition-physics3` in the name

**Comment by chapulina** [comment]
Ouch, let's go with #12

**Pull request closed without merging**
